public class GameBackend 
{
    private Character[] playerTeam;
    private Character[] enemyTeam;
    private String battleLog; // Was part of the debugEngine that I deleted (generated by claude to help me debug that problem and for future problems)
    // debugEngine has been gotten rid of, though, because I don't need it (it got way too complicated)
    // I don't actually know how battleLog & debugEngine works... it's just an AI program that helps me debug
    private boolean gameOver;
    private boolean playerWon;
    
    public GameBackend() 
    {
        battleLog = ""; // it's explained above
        gameOver = false;
        playerWon = false;
    }
    
    public void createTeams(int char1Index, int char2Index) 
    {
        Character knight = new Character("Knight", 250, 2, 30, 2, "Counter");
        Character robot = new Character("Robot", 300, 1, 35, 3, "Rocket");
        Character witch = new Character("Witch", 200, 3, 20, 5, "Revive");
        
        playerTeam = new Character[2];
        
        if (char1Index == 0)
        {
            playerTeam[0] = copyCharacter(knight); // copyCharacter is used (method right below this method) because we want
            // each Character to be a fresh independent objkect, not a reference to the same
        }
        else if (char1Index == 1)
        {
            playerTeam[0] = copyCharacter(robot);
        }
        else
        {
            playerTeam[0] = copyCharacter(witch);
        }
        playerTeam[0].name = "O's " + playerTeam[0].name;
        
        if (char2Index == 0)
        {
            playerTeam[1] = copyCharacter(knight);
        }
        else if (char2Index == 1)
        {
            playerTeam[1] = copyCharacter(robot);
        }
        else
        {
            playerTeam[1] = copyCharacter(witch);
        }
        playerTeam[1].name = "O's " + playerTeam[1].name; // 0 is put on so we can differentiate it from enemy's character if they
        // have the same character. Again, I didn't write this... Gemini did???? I think? For making it easy to debug in battleLog and debugEngine
        // we don't actually need this at all.
        
        enemyTeam = new Character[2];

        // selecting enemy choices
        int firstEnemyChoice = (int)(Math.random() * 3); // too many errors, so I had to ask... Gemini? I think?
        int secondEnemyChoice = (int)(Math.random() * 3);
        
        while (secondEnemyChoice == firstEnemyChoice)
        {
            secondEnemyChoice = (int)(Math.random() * 3);
        }
        
        if (firstEnemyChoice == 0)
        {
            enemyTeam[0] = copyCharacter(knight);
        }
        else if (firstEnemyChoice == 1)
        {
            enemyTeam[0] = copyCharacter(robot);
        }
        else
        {
            enemyTeam[0] = copyCharacter(witch);
        }
        enemyTeam[0].name = "X's " + enemyTeam[0].name;
        
        if (secondEnemyChoice == 0)
        {
            enemyTeam[1] = copyCharacter(knight);
        }
        else if (secondEnemyChoice == 1)
        {
            enemyTeam[1] = copyCharacter(robot);
        }
        else
        {
            enemyTeam[1] = copyCharacter(witch);
        }
        enemyTeam[1].name = "X's " + enemyTeam[1].name;
    }
    
    private Character copyCharacter(Character c) 
    {
        return new Character(c.name, c.maxHp, c.speed, c.attack, c.ultMax, c.ultName);
    }
    
    public void equipItem(int playerIndex, int itemIndex) 
    {
        String[] items = {"Shield", "Potion", "Knife", "Boots", "Blow Dart"};
        playerTeam[playerIndex].item = items[itemIndex];
        
        if (items[itemIndex].equals("Boots")) 
        {
            playerTeam[playerIndex].speed = playerTeam[playerIndex].speed + 2; // Boots get's a speed boost here.
        }
    }

    // all of these are for GameFrontend
    public Character[] getPlayerTeam() 
    { 
        return playerTeam; 
    }
    
    public Character[] getEnemyTeam() 
    { 
        return enemyTeam; 
    }
    
    public String getBattleLog() 
    { 
        return battleLog; 
    }
    
    public boolean isGameOver() 
    { 
        return gameOver; 
    }
    
    public boolean didPlayerWin() 
    { 
        return playerWon; 
    }

    
    public void playerAttack(int playerIndex, int enemyIndex) 
    {
        battleLog = "";
        Character attacker = playerTeam[playerIndex];
        Character target = enemyTeam[enemyIndex];
        
        if (!attacker.isAlive || !target.isAlive) // checks if one is dead or not
        {
            battleLog = "Invalid target!";
            return;
        }
        
        performAttack(attacker, target); 
        enemyTurn();
        endTurn(); // idk why this was here. I didn't write it... gemini may have had
    }
    
    public void playerUltimate(int playerIndex) // kinda the same thing as player attack a few lines above this...
    {
        battleLog = "";
        Character user = playerTeam[playerIndex];
        
        if (!user.isAlive || user.ultCharge < user.ultMax) 
        {
            
            battleLog = "Cannot use ultimate!";
            return;
            
        }
        
        useUltimate(user, playerTeam, enemyTeam);
        
        user.ultCharge = 0;
        
        enemyTurn();
        
        endTurn();
    }
    
    public void playerUseItem(int playerIndex) // Same as the method above, sorta
    {
        battleLog = "";
        Character user = playerTeam[playerIndex];
        
        if (!user.isAlive || user.item.equals("")) 
        {
            battleLog = "No item to use!";
            return;
        }
        
        useItem(user);
        enemyTurn();
        endTurn();
    }
    
    private void performAttack(Character attacker, Character target) 
    {
        int damage = attacker.attack;
        
        if (attacker.knifeBoostTurns > 0) 
        {
            damage = (int)(damage * 1.5);
        }
        
        if (target.shieldActive) 
        {
            battleLog = battleLog + target.name + " blocked with shield!\n";
            target.shieldActive = false;
            return;
        }
        
        target.currentHp = target.currentHp - damage;
        battleLog = battleLog + attacker.name + " attacks " + target.name + " for " + damage + " damage!\n";
        
        if (attacker.name.contains("Witch")) 
        {
            target.poisonTurns = 3;
            battleLog = battleLog + target.name + " is poisoned!\n";
        }
        
        checkDeath(target);
    }
    
    private void useUltimate(Character user, Character[] allies, Character[] enemies) 
    {
        battleLog = battleLog + user.name + " uses " + user.ultName + "!\n";
        
        if (user.name.contains("Knight")) 
        {
            user.shieldActive = true;
            battleLog = battleLog + user.name + " raises shield!\n";
            
        } 
        else if (user.name.contains("Robot")) 
        {
            int i = 0;
            while (i < enemies.length)
            {
                if (enemies[i].isAlive) 
                {
                    enemies[i].currentHp = enemies[i].currentHp - 50;
                    battleLog = battleLog + "Rocket hits " + enemies[i].name + " for 50 damage!\n";
                    checkDeath(enemies[i]);
                }
                i = i + 1;
            }
            
        } 
        else if (user.name.contains("Witch")) 
        {
            boolean isAlive = false;
            int i = 0;
            while (i < allies.length)
            {
                if (!allies[i].isAlive) 
                {
                    allies[i].currentHp = 50;
                    allies[i].isAlive = true;
                    battleLog = battleLog + allies[i].name + " isAlive with 50 HP!\n";
                    isAlive = true;
                    break;
                }
                i = i + 1;
            }
            
            if (!isAlive) 
            {
                int j = 0;
                while (j < allies.length)
                {
                    if (allies[j].isAlive && allies[j] != user) 
                    {
                        allies[j].currentHp = allies[j].currentHp + 20;
                        if (allies[j].currentHp > allies[j].maxHp) 
                        {
                            allies[j].currentHp = allies[j].maxHp;
                        }
                        battleLog = battleLog + allies[j].name + " healed for 20 HP!\n";
                        return;
                    }
                    j = j + 1;
                }
            }
        }
    }
    
    private void useItem(Character user) 
    {
        battleLog = battleLog + user.name + " uses " + user.item + "!\n";
        
        if (user.item.equals("Potion")) 
        {
            user.currentHp = user.currentHp + 40;
            if (user.currentHp > user.maxHp) 
            {
                user.currentHp = user.maxHp;
            }
            battleLog = battleLog + user.name + " heals 40 HP!\n";
            user.item = "";
            
        } 
        else if (user.item.equals("Shield")) 
        {
            user.shieldActive = true;
            battleLog = battleLog + user.name + " raises shield!\n";
            user.item = "";
            
        } 
        else if (user.item.equals("Knife")) 
        {
            user.knifeBoostTurns = 2;
            battleLog = battleLog + user.name + " gets +50% damage for 2 turns!\n";
            user.item = "";
        }
    }
    
    private void enemyTurn() 
    {
        int i = 0;
        while (i < enemyTeam.length)
        {
            if (!enemyTeam[i].isAlive) 
            {
                i = i + 1;
                continue;
            }
            
            Character target = null;
            if (playerTeam[0].isAlive && playerTeam[1].isAlive) 
            {
                target = playerTeam[(int)(Math.random() * 2)];
            } 
            else if (playerTeam[0].isAlive) 
            {
                target = playerTeam[0];
            } 
            else if (playerTeam[1].isAlive) 
            {
                target = playerTeam[1];
            }
            
            if (target != null) 
            {
                if (enemyTeam[i].ultCharge >= enemyTeam[i].ultMax && (int)(Math.random() * 100) < 30) 
                {
                    useUltimate(enemyTeam[i], enemyTeam, playerTeam);
                    enemyTeam[i].ultCharge = 0;
                } 
                else 
                {
                    performAttack(enemyTeam[i], target);
                }
            }
            i = i + 1;
        }
    }
    

    private void endTurn() 
    {
        int i = 0;
        while (i < playerTeam.length)
        {
            if (playerTeam[i].poisonTurns > 0) 
            {
                playerTeam[i].currentHp = playerTeam[i].currentHp - 10;
                battleLog = battleLog + playerTeam[i].name + " takes 10 poison damage!\n";
                playerTeam[i].poisonTurns = playerTeam[i].poisonTurns - 1;
                checkDeath(playerTeam[i]);
            }
            i = i + 1;
        }
    
        i = 0;
        while (i < enemyTeam.length)
        {
            if (enemyTeam[i].poisonTurns > 0) 
            {
                enemyTeam[i].currentHp = enemyTeam[i].currentHp - 10;
                battleLog = battleLog + enemyTeam[i].name + " takes 10 poison damage!\n";
                enemyTeam[i].poisonTurns = enemyTeam[i].poisonTurns - 1;
                checkDeath(enemyTeam[i]);
            }
            i++;
        }

        i = 0;
        while (i < playerTeam.length)
        {
            if (playerTeam[i].knifeBoostTurns > 0) 
            {
                playerTeam[i].knifeBoostTurns = playerTeam[i].knifeBoostTurns - 1;
            }
            i++;
        }

        i = 0;
        while (i < enemyTeam.length)
        {
            if (enemyTeam[i].knifeBoostTurns > 0) 
            {
                enemyTeam[i].knifeBoostTurns = enemyTeam[i].knifeBoostTurns - 1;
            }    
            i++;
        }

        i = 0;
        while (i < playerTeam.length)
        {
            if (playerTeam[i].isAlive && playerTeam[i].ultCharge < playerTeam[i].ultMax) 
            {
                playerTeam[i].ultCharge = playerTeam[i].ultCharge + 1;
            }
            i++;
        }

        i = 0;
        while (i < enemyTeam.length)
        {
            
            if (enemyTeam[i].isAlive && enemyTeam[i].ultCharge < enemyTeam[i].ultMax) 
            {
                enemyTeam[i].ultCharge = enemyTeam[i].ultCharge + 1;
            }
            i++;
        }
    
        checkGameOver();
    }

    
    private void checkDeath(Character c) 
    {
        if (c.currentHp <= 0) 
        {
            
            c.currentHp = 0;
            c.isAlive = false;
            battleLog = battleLog + c.name + " has been defeated!\n";
            
        }
    }
    
    private void checkGameOver() 
    {
        
        boolean playerAlive = playerTeam[0].isAlive || playerTeam[1].isAlive;
        boolean enemyAlive = enemyTeam[0].isAlive || enemyTeam[1].isAlive;
        
        if (!playerAlive) 
        {
            
            gameOver = true;
            playerWon = false;
            battleLog = battleLog + "\n*** GAME OVER - You Lost! ***\n";
            
        } 
        else if (!enemyAlive) 
        {
            gameOver = true;
            playerWon = true;
            battleLog = battleLog + "\n*** VICTORY - You Won! ***\n";
        }
    }
}
